spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    activate:
      on-profile: front-prod
    import: classpath:application-core-prod.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://myfluffy.com/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

# 커스텀 설정
app:
  oauth:
    redirect-uri: https://myfluffy.com
  is-local: false

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:https://myfluffy.com}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000