spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    activate:
      on-profile: front
    import: classpath:application-core.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            redirect-uri: "http://localhost:8082/login/oauth2/code/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8082

# 커스텀 설정
app:
  oauth:
    redirect-uri: http://localhost:5174
  is-local: true

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5174}

security:
  jwt:
    secret-key: "yourJwtSecretKey"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000