spring:
  config:
    import: classpath:application-core.yml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

redis:
  host: localhost
  port: 6379
  timeout: 6000ms
  lettuce:
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: 5000ms

web:
  resources:
    static-locations:
      - classpath:/static/
      - file:/Users/myAccount/Desktop/myFluffy-uploads/

security:
  jwt:
    secret-key: "yourJwtSecretKey"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}

logging:
  level:
    org.springframework.security: DEBUG