spring:
  config:
    activate:
      on-profile: admin-prod
    import: classpath:application-core-prod.yml

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 15MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 5000ms

server:
  port: 443
  ssl:
    enabled: true
    key-store: ${SSL_KEY_STORE:file:/home/ubuntu/cms.myfluffy.site.p12}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: "${KEYSTORE_PASSWORD:defaultPassword}"
    key-alias: ${SSL_KEY_ALIAS:cms}
  error:
    include-stacktrace: never      # trace 숨김
    include-message: always        # message 노출

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:https://cms.myfluffy.site}

file:
  upload:
    base-dir: ${FILE_UPLOAD_BASE_DIR:/home/ubuntu/myFluffy-uploads}
    base-url: ${FILE_UPLOAD_BASE_URL:/uploads/images}

logging:
  level:
    org.springframework.security: INFO