spring:
  config:
    activate:
      on-profile: admin-prod
    import: classpath:application-core-prod.yml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  timeout: 6000ms
  lettuce:
    pool:
      max-active: 10
      max-idle: 5
      min-idle: 2
      max-wait: 5000ms

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN:https://admin.myfluffy.com}

logging:
  level:
    org.springframework.security: INFO