spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myfluffy
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mysql/*.xml
  type-aliases-package: com.renee328.dto
  type-handlers-package: com.renee328.handler

web:
  resources:
    static-locations:
      - classpath:/static/
      - file:/Users/YourAccount/Desktop/myFluffy-uploads/

logging:
  level:
    org.mybatis: DEBUG
    com.renee328.mapper: DEBUG