spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/myfluffy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/mysql/*.xml
  type-aliases-package: com.renee328.dto
  type-handlers-package: com.renee328.handler

web:
  resources:
    static-locations:
      - classpath:/static/
      - file:/home/ubuntu/myFluffy-uploads/

logging:
  level:
    org.mybatis: INFO
    com.renee328.mapper: INFO